name: build-deploy-staging
on:
  push:
    branches:
      - 'develop'
      - '!master'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  build-staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 16
      - run: npm install
      - run: npm run starterkit:build
      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: |
            dist

  test-staging:
    needs: build-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: |
            dist         
      - run: |
          # npm install -g pa11y-ci
          # pa11y-ci ./dist/{components,core,templates}/**/index.html ./dist/{components,core}/**/blank.html
  deploy-staging:
    needs: test-staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm install -g surge
      - uses: actions/download-artifact@v5
        with:
          name: dist
          path: |
            dist
      - run: surge ./dist ${{ secrets.SURGE_DOMAIN_STAGING }} --token ${{ secrets.SURGE_TOKEN }}
