name: build-deploy-v3
on:
  push:
    branches:
      - 'feature/version-3'
      - '!master'
jobs:
  build-v3:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - run: npm install
      - run: npm run starterkit:build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist

  test-v3:
    needs: build-v3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: |
            dist
      - run: |
          npm install -g pa11y-ci
          pa11y-ci ./dist/{components,styles,templates}/**/index.html ./dist/{components,styles}/**/blank.html
      - name: Visual test
        run: npx percy snapshot dist/ --ignore-files "{components,styles}/**/index.html"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  deploy-v3:
    needs: test-v3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm install -g surge
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: |
            dist
      - run: surge ./dist nswdesignsystem-v3.surge.sh --token ${{ secrets.SURGE_TOKEN }}
